"""spoo — Official Python SDK for the spoo.me URL shortening API."""

from ._client import AsyncSpooClient
from ._errors import (
    APIConnectionError,
    APIError,
    APITimeoutError,
    AuthenticationError,
    ConflictError,
    ContentBlockedError,
    ForbiddenError,
    GoneError,
    InternalServerError,
    NotFoundError,
    PayloadTooLargeError,
    RateLimitError,
    ServiceUnavailableError,
    SessionExpiredError,
    SpooError,
    ValidationError,
)
from ._pkce import PkcePair, generate_pkce_pair, generate_state
from ._sync_client import SpooClient
from ._version import __version__
from .types import (
    AliasCheck,
    AliasType,
    BulkDeletedLinks,
    BulkResult,
    BulkResultRow,
    BulkSummary,
    ClaimedLinks,
    ClaimResult,
    ComputedMetrics,
    CreatedLink,
    DeletedLink,
    EmojiEntry,
    EmojiSet,
    ExportFile,
    ExportFormat,
    GroupBy,
    Link,
    LinkFilter,
    LinkPage,
    LinkStatsFilter,
    LinkStatsResponse,
    LinkStatus,
    Metric,
    OAuthTokens,
    PreviewDestination,
    PublicLinkFacts,
    PublicPreview,
    PublicStatsResponse,
    SortBy,
    SortOrder,
    StatsFilter,
    StatsResponse,
    StatsSummary,
    StatsTimeRange,
    TimeBucketInfo,
    UpdatedLink,
    UserProfile,
)

__all__ = [
    # Clients
    "AsyncSpooClient",
    "SpooClient",
    # Errors
    "APIConnectionError",
    "APIError",
    "APITimeoutError",
    "AuthenticationError",
    "ConflictError",
    "ForbiddenError",
    "ContentBlockedError",
    "GoneError",
    "InternalServerError",
    "ServiceUnavailableError",
    "NotFoundError",
    "PayloadTooLargeError",
    "RateLimitError",
    "SessionExpiredError",
    "SpooError",
    "ValidationError",
    # OAuth helpers
    "PkcePair",
    "generate_pkce_pair",
    "generate_state",
    # Types
    "AliasCheck",
    "AliasType",
    "BulkDeletedLinks",
    "BulkResult",
    "BulkResultRow",
    "BulkSummary",
    "ClaimResult",
    "ClaimedLinks",
    "ComputedMetrics",
    "DeletedLink",
    "EmojiEntry",
    "EmojiSet",
    "ExportFile",
    "ExportFormat",
    "GroupBy",
    "LinkStatsFilter",
    "LinkStatsResponse",
    "Metric",
    "OAuthTokens",
    "PreviewDestination",
    "PublicLinkFacts",
    "PublicPreview",
    "PublicStatsResponse",
    "CreatedLink",
    "SortBy",
    "SortOrder",
    "StatsFilter",
    "StatsResponse",
    "StatsSummary",
    "StatsTimeRange",
    "TimeBucketInfo",
    "UpdatedLink",
    "LinkFilter",
    "Link",
    "LinkPage",
    "LinkStatus",
    "UserProfile",
    # Version
    "__version__",
]
