"""spoo — Official Python SDK for the spoo.me URL shortening API."""

from ._client import AsyncSpooClient
from ._errors import (
    APIConnectionError,
    APIError,
    APITimeoutError,
    AuthenticationError,
    ConflictError,
    ForbiddenError,
    GoneError,
    InternalServerError,
    NotFoundError,
    RateLimitError,
    SessionExpiredError,
    SpooError,
    ValidationError,
)
from ._pkce import PkcePair, generate_pkce_pair, generate_state
from ._sync_client import SpooClient
from ._version import __version__
from .types import (
    AliasCheck,
    AliasType,
    BulkDeletedUrls,
    BulkResult,
    BulkResultRow,
    BulkSummary,
    ClaimedUrls,
    ClaimResult,
    ComputedMetrics,
    DeletedUrl,
    EmojiEntry,
    EmojiSet,
    ExportFormat,
    GroupBy,
    LinkStatsResponse,
    Metric,
    OAuthTokens,
    PublicLinkFacts,
    PublicStatsResponse,
    ShortenedUrl,
    SortBy,
    SortOrder,
    StatsFilter,
    StatsResponse,
    StatsSummary,
    StatsTimeRange,
    TimeBucketInfo,
    UpdatedUrl,
    UrlFilter,
    UrlListItem,
    UrlListResponse,
    UrlStatus,
    UserProfile,
)

__all__ = [
    # Clients
    "AsyncSpooClient",
    "SpooClient",
    # Errors
    "APIConnectionError",
    "APIError",
    "APITimeoutError",
    "AuthenticationError",
    "ConflictError",
    "ForbiddenError",
    "GoneError",
    "InternalServerError",
    "NotFoundError",
    "RateLimitError",
    "SessionExpiredError",
    "SpooError",
    "ValidationError",
    # OAuth helpers
    "PkcePair",
    "generate_pkce_pair",
    "generate_state",
    # Types
    "AliasCheck",
    "AliasType",
    "BulkDeletedUrls",
    "BulkResult",
    "BulkResultRow",
    "BulkSummary",
    "ClaimResult",
    "ClaimedUrls",
    "ComputedMetrics",
    "DeletedUrl",
    "EmojiEntry",
    "EmojiSet",
    "ExportFormat",
    "GroupBy",
    "LinkStatsResponse",
    "Metric",
    "OAuthTokens",
    "PublicLinkFacts",
    "PublicStatsResponse",
    "ShortenedUrl",
    "SortBy",
    "SortOrder",
    "StatsFilter",
    "StatsResponse",
    "StatsSummary",
    "StatsTimeRange",
    "TimeBucketInfo",
    "UpdatedUrl",
    "UrlFilter",
    "UrlListItem",
    "UrlListResponse",
    "UrlStatus",
    "UserProfile",
    # Version
    "__version__",
]
